### ISSUE TITLE
404 GET /static/components/codemirror/mode/ihaskell/ihaskell.js

### ISSUE THREAD

**Issue by bsmith89** [gibiansky/IHaskell#521]
As mentioned in #516, opening an IHaskell notebook yields:

```
$ ipython notebook
[I 22:55:31.410 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
[I 22:55:31.435 NotebookApp] Serving notebooks from local directory: /Users/bjsmith/Projects/seq-div/ipynb
[I 22:55:31.436 NotebookApp] 0 active kernels
[I 22:55:31.436 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 22:55:31.436 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 22:55:35.680 NotebookApp] Creating new notebook in
[I 22:55:36.865 NotebookApp] Kernel started: 68140913-a921-46c1-975d-75d1a8b993c8
[W 22:55:37.036 NotebookApp] 404 GET /static/components/codemirror/mode/ihaskell/ihaskell.js?v=20150629225531 (::1) 1.14ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=haskell
Header: {"username":"bjsmith","date":"2015-06-29T22:55:36.900743","version":"5.0","msg_type":"kernel_info_request","session":"7192577F8C6244BB9364B40C2D30A01A","msg_id":"2d4504c7-e815-4b1d-9751-c3b50cfbe7a2"}
Content: {}
Message: KernelInfoReply {header = MessageHeader {identifiers = ["\NULD1\183\130"], parentHeader = Just (MessageHeader {identifiers = ["\NULD1\183\130"], parentHeader = Nothing, metadata = fromList [], messageId = UUID "2d4504c7-e815-4b1d-9751-c3b50cfbe7a2", sessionId = UUID "7192577F8C6244BB9364B40C2D30A01A", username = "bjsmith", msgType = KernelInfoRequestMessage}), metadata = fromList [], messageId = UUID "6ea230fe-98bb-4eb6-bb36-6e44c0490ce1", sessionId = UUID "7192577F8C6244BB9364B40C2D30A01A", username = "bjsmith", msgType = KernelInfoReplyMessage}, versionList = [7,8,4], language = "haskell"}
Sent: "{\"language_version\":[7,8,4],\"protocol_version\":\"5.0\",\"language\":\"haskell\"}"
Header: {"version":"5.0","username":"username","msg_type":"kernel_info_request","session":"7192577F8C6244BB9364B40C2D30A01A","msg_id":"18A5FDB95ED94DEF9F04898D74C2FAD6"}
Content: {}
Message: KernelInfoReply {header = MessageHeader {identifiers = ["7192577F8C6244BB9364B40C2D30A01A"], parentHeader = Just (MessageHeader {identifiers = ["7192577F8C6244BB9364B40C2D30A01A"], parentHeader = Nothing, metadata = fromList [], messageId = UUID "18A5FDB95ED94DEF9F04898D74C2FAD6", sessionId = UUID "7192577F8C6244BB9364B40C2D30A01A", username = "username", msgType = KernelInfoRequestMessage}), metadata = fromList [], messageId = UUID "918806e8-8b4a-4f19-8216-5466f5ce1687", sessionId = UUID "7192577F8C6244BB9364B40C2D30A01A", username = "username", msgType = KernelInfoReplyMessage}, versionList = [7,8,4], language = "haskell"}
Sent: "{\"language_version\":[7,8,4],\"protocol_version\":\"5.0\",\"language\":\"haskell\"}"

```

I'm curious if that 404 on `/static/components/codemirror/mode/ihaskell/ihaskell.js` is related to #481.

**Comment by bsmith89** [comment]
@gibiansky You wrote on the previous issue:
> What happens if you run ipython notebook and then try to execute a command? What is the output in the console?

When I open up an IHaskell Notebook and run

```
a = 10
a
```

the full logging/debugging output to the console is:

```
[W 12:15:05.690 NotebookApp] 404 GET /static/components/codemirror/mode/ihaskell/ihaskell.js?v=20150706121447 (::1) 1.39ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=haskell
Header: {"date":"2015-07-06T12:15:05.551189","username":"bjsmith","msg_id":"16e2a5a2-467b-4462-bfd1-a64dc7e65a9e","session":"0EC36E1F667E496A91EBC72951511396","msg_type":"kernel_info_request","version":"5.0"}
Content: {}
Message: KernelInfoReply {header = MessageHeader {identifiers = ["\NULD1\183\130"], parentHeader = Just (MessageHeader {identifiers = ["\NULD1\183\130"], parentHeader = Nothing, metadata = fromList [], messageId = UUID "16e2a5a2-467b-4462-bfd1-a64dc7e65a9e", sessionId = UUID "0EC36E1F667E496A91EBC72951511396", username = "bjsmith", msgType = KernelInfoRequestMessage}), metadata = fromList [], messageId = UUID "7b3fdfe5-991a-4748-aa2e-aeae28146cbf", sessionId = UUID "0EC36E1F667E496A91EBC72951511396", username = "bjsmith", msgType = KernelInfoReplyMessage}, versionList = [7,8,4], language = "haskell"}
Sent: "{\"language_version\":[7,8,4],\"protocol_version\":\"5.0\",\"language\":\"haskell\"}"
Header: {"version":"5.0","session":"0EC36E1F667E496A91EBC72951511396","msg_id":"CD1A335E50694736A41BA5D5E48EFC07","msg_type":"kernel_info_request","username":"username"}
Content: {}
Message: KernelInfoReply {header = MessageHeader {identifiers = ["0EC36E1F667E496A91EBC72951511396"], parentHeader = Just (MessageHeader {identifiers = ["0EC36E1F667E496A91EBC72951511396"], parentHeader = Nothing, metadata = fromList [], messageId = UUID "CD1A335E50694736A41BA5D5E48EFC07", sessionId = UUID "0EC36E1F667E496A91EBC72951511396", username = "username", msgType = KernelInfoRequestMessage}), metadata = fromList [], messageId = UUID "028918ec-fd5b-4fd6-a8ef-c3532883a1ec", sessionId = UUID "0EC36E1F667E496A91EBC72951511396", username = "username", msgType = KernelInfoReplyMessage}, versionList = [7,8,4], language = "haskell"}
Sent: "{\"language_version\":[7,8,4],\"protocol_version\":\"5.0\",\"language\":\"haskell\"}"
Header: {"version":"5.0","session":"0EC36E1F667E496A91EBC72951511396","msg_id":"2B041DBF04954A2EA5A87F506F420B81","msg_type":"execute_request","username":"username"}
Content: {"store_history":true,"allow_stdin":true,"code":"a = 10\na","silent":false,"stop_on_error":true,"user_expressions":{}}
Message: PublishStatus {header = MessageHeader {identifiers = ["0EC36E1F667E496A91EBC72951511396"], parentHeader = Just (MessageHeader {identifiers = ["0EC36E1F667E496A91EBC72951511396"], parentHeader = Nothing, metadata = fromList [], messageId = UUID "2B041DBF04954A2EA5A87F506F420B81", sessionId = UUID "0EC36E1F667E496A91EBC72951511396", username = "username", msgType = ExecuteRequestMessage}), metadata = fromList [], messageId = UUID "39c23cca-76e1-41ac-8533-2a57a19daf72", sessionId = UUID "0EC36E1F667E496A91EBC72951511396", username = "username", msgType = StatusMessage}, executionState = Busy}
Sent: "{\"execution_state\":\"busy\"}"
Message: PublishInput {header = MessageHeader {identifiers = ["0EC36E1F667E496A91EBC72951511396"], parentHeader = Just (MessageHeader {identifiers = ["0EC36E1F667E496A91EBC72951511396"], parentHeader = Nothing, metadata = fromList [], messageId = UUID "2B041DBF04954A2EA5A87F506F420B81", sessionId = UUID "0EC36E1F667E496A91EBC72951511396", username = "username", msgType = ExecuteRequestMessage}), metadata = fromList [], messageId = UUID "a1cbc6f3-52ff-4c39-a777-9a668bce05b4", sessionId = UUID "0EC36E1F667E496A91EBC72951511396", username = "username", msgType = InputMessage}, inCode = "a = 10\na", executionCount = 1}
Sent: "{\"execution_count\":1,\"code\":\"a = 10\\na\"}"
DEBUG: Declaration:
a = 10
DEBUG: Expression:
a
DEBUG: Can Display: False
DEBUG: Is Widget: False
DEBUG: Is Declaration: False
DEBUG: Statement:
a
DEBUG: Names: ["it"]
Message: ClearOutput {header = MessageHeader {identifiers = ["0EC36E1F667E496A91EBC72951511396"], parentHeader = Just (MessageHeader {identifiers = ["0EC36E1F667E496A91EBC72951511396"], parentHeader = Nothing, metadata = fromList [], messageId = UUID "2B041DBF04954A2EA5A87F506F420B81", sessionId = UUID "0EC36E1F667E496A91EBC72951511396", username = "username", msgType = ExecuteRequestMessage}), metadata = fromList [], messageId = UUID "e03cb020-c9a9-4090-ae05-38e097e802f1", sessionId = UUID "0EC36E1F667E496A91EBC72951511396", username = "username", msgType = ClearOutputMessage}, wait = True}
Sent: "{\"wait\":true}"
Message: PublishDisplayData {header = MessageHeader {identifiers = ["0EC36E1F667E496A91EBC72951511396"], parentHeader = Just (MessageHeader {identifiers = ["0EC36E1F667E496A91EBC72951511396"], parentHeader = Nothing, metadata = fromList [], messageId = UUID "2B041DBF04954A2EA5A87F506F420B81", sessionId = UUID "0EC36E1F667E496A91EBC72951511396", username = "username", msgType = ExecuteRequestMessage}), metadata = fromList [], messageId = UUID "12dcce4b-786a-4003-bf0f-915709aaacd6", sessionId = UUID "0EC36E1F667E496A91EBC72951511396", username = "username", msgType = DisplayDataMessage}, source = "haskell", displayData = [DisplayData]}
Sent: "{\"data\":{\"text/plain\":\"10\\nMessage: PublishDisplayData {header = MessageHeader {identifiers = [\\\"0EC36E1F667E496A91EBC72951511396\\\"], parentHeader = Just (MessageHeader {identifiers = [\\\"0EC36E1F667E496A91EBC72951511396\\\"], parentHeader = Nothing, metadata = fromList [], messageId = UUID \\\"2B041DBF04954A2EA5A87F506F420B81\\\", sessionId = UUID \\\"0EC36E1F667E496A91EBC72951511396\\\", username = \\\"username\\\", msgType = ExecuteRequestMessage}), metadata = fromList [], messageId = UUID \\\"8200b4be-d8be-4e5d-9cc7-c6f73355d610\\\", sessionId = UUID \\\"0EC36E1F667E496A91EBC72951511396\\\", username = \\\"username\\\", msgType = DisplayDataMessage}, source = \\\"haskell\\\", displayData = [DisplayData]}\\nSent: \\\"{\\\\\\\"data\\\\\\\":{\\\\\\\"text/plain\\\\\\\":\\\\\\\"10\\\\\\\"},\\\\\\\"metadata\\\\\\\":{},\\\\\\\"source\\\\\\\":\\\\\\\"haskell\\\\\\\"}\\\"\"},\"metadata\":{},\"source\":\"haskell\"}"
DEBUG: Statement:
let it1 = it
DEBUG: Names: ["it1"]
Message: PublishStatus {header = MessageHeader {identifiers = ["0EC36E1F667E496A91EBC72951511396"], parentHeader = Just (MessageHeader {identifiers = ["0EC36E1F667E496A91EBC72951511396"], parentHeader = Nothing, metadata = fromList [], messageId = UUID "2B041DBF04954A2EA5A87F506F420B81", sessionId = UUID "0EC36E1F667E496A91EBC72951511396", username = "username", msgType = ExecuteRequestMessage}), metadata = fromList [], messageId = UUID "70b781f2-ac54-46ff-9f40-424b311c9b46", sessionId = UUID "0EC36E1F667E496A91EBC72951511396", username = "username", msgType = StatusMessage}, executionState = Idle}
Sent: "{\"execution_state\":\"idle\"}"
Message: ExecuteReply {header = MessageHeader {identifiers = ["0EC36E1F667E496A91EBC72951511396"], parentHeader = Just (MessageHeader {identifiers = ["0EC36E1F667E496A91EBC72951511396"], parentHeader = Nothing, metadata = fromList [], messageId = UUID "2B041DBF04954A2EA5A87F506F420B81", sessionId = UUID "0EC36E1F667E496A91EBC72951511396", username = "username", msgType = ExecuteRequestMessage}), metadata = fromList [], messageId = UUID "5c8d444f-2b00-4771-9eba-620358df9e0b", sessionId = UUID "0EC36E1F667E496A91EBC72951511396", username = "username", msgType = ExecuteReplyMessage}, status = ok, pagerOutput = [DisplayData], executionCounter = 1}
Sent: "{\"status\":\"ok\",\"user_expressions\":{},\"user_variables\":{},\"execution_count\":1,\"payload\":[{\"data\":{\"text/plain\":\"\"},\"line\":0,\"source\":\"page\"}]}"
```

**Comment by gibiansky** [comment]
@bsmith89 Does it not print `10` to the output?

Is the issue here just the 404 (and the resulting lack of proper syntax coloring in some places), or is it not responding to requests?

**Comment by bsmith89** [comment]
Yes, it prints `10` to the output in the notebook.

**Comment by aueelis** [comment]
The `404` vanished for me after updating to `ihaskell 0.6.4.0`.

**Comment by gibiansky** [comment]
Underlying issue (#481) should be fixed.

**Comment by mietek** [comment]
`/static/components/codemirror/mode/ihaskell/ihaskell.js` is still missing. The following message appears every time I open a Haskell notebook:
```
21:21:08 ~ $ jupyter notebook
[I 21:21:17.333 NotebookApp] Serving notebooks from local directory: /Users/mietek
[I 21:21:17.333 NotebookApp] 0 active kernels 
[I 21:21:17.333 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 21:21:17.333 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 21:21:25.947 NotebookApp] Creating new notebook in 
[I 21:21:26.336 NotebookApp] Kernel started: a0c0225c-c260-4646-a298-b467605226f2
[W 21:21:26.454 NotebookApp] 404 GET /static/components/codemirror/mode/ihaskell/ihaskell.js (127.0.0.1) 12.65ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=haskell
```

**Comment by mietek** [comment]
Sorry, never mind. This happens when `ihaskell-widgets` is not installed within the Cabal sandbox.
